### PR TITLE
Lab#2

### PR DESCRIPTION
**Pull request by hmyin516**
@nsyochum 
Here is the initial version for review

### CODE REVIEW

**Comment by nsyochum** [comment]
# Problem 1

**a/b** LGTM

**C)** It's hard to what is going on with the graph, it might help to shrink the x axis or have fewer overlapping functions.  Also consider plotting your final poisson distribution on the same graph as your gaussian comparison.  
  
**D)** you have this line:  
  
    dist = stats.poisson.pmf(x,mu)  
  
But I don't see where `mu` is defined  
  
# Problem 2  
**A)**  It's hard to read the graphs  
**B)** It's hard to tell what the point of these graphs are.  
  
# Problem 3  
**Version 1** It says to pick a floating point number and not an integer (not really a big deal).  Also, your sigma should be positive and not negative.  
  
**Version 2**  
**B)** You didn't actually state a question.  
**C)** I'm not sure your methodology here is quite valid.  
  
# Problem 4  
**A)** there is a more direct way of doing this that was discussed in lecture.  Your way is mildly convoluted.  
**B)** Same as A  
**C/D)** You didn't explain this

**Comment by hmyin516** [comment]
@AlexSchuy  Lab 2 turn in

**Comment by hmyin516** [comment]
@AlexSchuy 7hrs

**Comment by AlexSchuy** [comment]
Hello, here are my comments for lab 2:

**Problem 1**

1.A) This problem is essentially equivalent to the dice in HW2, except this time you should convolve the Poisson distribution.

1.B) The idea is that the Poisson distribution describes the number of events in some time interval, where the events occur independently of each other with some constant average rate. Since the events are independent and constant in rate, it makes sense that we can add Poisson distributions over short intervals together to get a Poisson distribution for a longer interval. Note that adding Poisson distributions will definitely change the shape, not just the scale.

1.C) Too many distributions shown in one plot; it's very hard to read. Pick a few that nicely illustrate your point and stick with those. Also, note that summing and averaging are essentially the same operation, except for a scale factor; in both cases, you need to use the convolution operator. As for the Gaussian plot, you should also overlay that with a Poisson plot to show that they are similar.

1.D) Now that you know the sum of Poisson distributions is also Poisson, you should just use a single Poisson distribution for the N days and calculate sigma as you have previously (integrate the Poisson distribution as appropriate--in this case, from the measured value Y*N to infinity--and convert that to a sigma using the normal distribution). 

**Problem 2**

Make sure that the distribution is still normalized after your convolutions. Also, plot the Gaussian overlaid with your Rayleigh to illustrate that the two are close.

**Problem 3: Version 1**

It looks like you plotted the mean of the background to be 50000, not the width.

**Problem 3: Version 2**

3.B) Since the signal can be in any pixel, instead of just one, we ask what the probability is of observing a measurement as large as our signal in any of the pixels.

**Problem 4**

The idea is to go in reverse here. I know I want a 5-sigma detection. I can convert that into a probability by integrating the standard normal distribution from 5 to infinity. Then, I can convert the probability to a required signal brightness by asking from what point in my background distribution I need to integrate from to get this probability. 

Remember that the pdf is (roughly) scaled up for version 2 by a factor of 10k for points far in the tail. Thus, inverting the cdf of version 2 for a probability is roughly equivalent to inverting the cdf of version 1 for that probability / 10000.  The probability integrating from the left is then 1 - probability / 10000, which is not the same as (1 - probability) / 10000. The former case is closer to 1, which leads to the brightness needing to be larger, as we expect. The latter case is further from 1 (dramatically so), which leads to the brightness not needing to be as large, which is nonsensical.

The idea of this problem is that the more places I look, the more likely it is that I'll find something, even if it isn't really there. If I see a signal that only has a 1 in a million chance according to my background, I feel pretty confident that my background is not entirely correct. However, if I look a million times, then even if my background **is** correct, I expect, on average, to see such an event once.

However, because the Gaussian distribution falls off so quickly towards the tails, it turns out that I do not need to record that much larger of a signal in order to again be fairly certain that my background is incorrect.

**Pull request merged**
